baseurl = "https://example.org/"
absURL = "https://example.org/"
languageCode = "en-us"
title = "Xavier Escudero Sabadell"
googleAnalytics = ""
idea="https://themes.gohugo.io/theme/creative/"

[params]
	name = "Xavier Escudero"
	description = "Your description"

# Navigation
[params.navigation]
	brand = "Xavier Escudero Sabadell"

	[params.navigation.links]
		about     = "About"
		resume 	  = "Resumé"
		services  = "Education"
		portfolio = "Portfolio"
		contact   = "Contact"
