backend:
  name: github
  repo: xescuder/xescuder-personalsite

media_folder: src/content/img
public_folder: assets

collections:
  - name: post
    label: Post
    folder: src/content
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { name: title, label: title }
      - { name: author, label: author }
      - { name: tags, label: Tags, widget: list, default: ['testing']}
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }

